### PR TITLE
Update version to latest LTS

### PR DESCRIPTION
**Pull request by p-zubieta**

### CODE REVIEW

**Review by ararslan — APPROVED** [review]
Seems reasonable. FYI we may need to tweak things to match https://github.com/mrcinv/julia-snap in order to fix the 32-bit Julia on 64-bit Linux issue.

**Comment by p-zubieta** [comment]
Modified that bit as well. Should be good now.

**Comment by ararslan** [comment]
Feel free to merge at your leisure. 🙂 Let me know if you run into any issues deploying. I wonder if it's something we could set up to deploy automatically from GitHub Actions...

**Comment by p-zubieta** [comment]
> Let me know if you run into any issues deploying.

Will do, thanks! :slightly_smiling_face:

> I wonder if it's something we could set up to deploy automatically from GitHub Actions...

Yeah, that would make more sense. I'll think about it.

**Pull request merged**
