### PR TITLE
Auto-generate the YAML file that describes the version

### PR DESCRIPTION
**Pull request by ararslan**
Currently we have separate, almost entirely identical files, `snapcraft-lts.yaml` and `snapcraft-stable.yaml`, and on CI we copy the appropriate one to `snapcraft.yaml`. This requires keeping the patch versions of both LTS and stable up to date, as both are hard-coded in their respective files.

Instead, we can automatically generate `snapcraft.yaml` based on the release type (`lts` or `stable`) and `versions.json`. This allows us to select the most recent LTS patch or stable version without needing to edit anything directly.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
I was thinking of just having a `snapcraft.yml.in` file that has `version: 'JULIA_VERSION_PLACEHOLDER'`, and then in Julia do a `replace(str, "JULIA_VERSION_PLACEHOLDER" => julia_version`. That might be easier to read.

**Comment by ararslan** [comment]
The URLs differ though, so we'd need a second placeholder value.

**Comment by p-zubieta** [comment]
You could have this, I think

```
name: julia
version: ${JULIA_VERSION}
title: The Julia Language
summary: The Julia programming language
description: |
  Julia is a high level, high performance, dynamic language for technical computing.
license: MIT

base: core18
confinement: classic
grade: stable
type: app

architectures:
- build-on: amd64
- build-on: i386
- build-on: arm64
- build-on: armhf

apps:
  julia:
    command: bin/julia
  julia-docs:
    command: julia-docs.sh $SNAP/share/doc/julia/html/en/index.html

parts:
  julia:
    plugin: dump
    source:
    - on amd64: https://julialang-s3.julialang.org/bin/linux/x64/${JULIA_RELEASE}/julia-$SNAPCRAFT_PROJECT_VERSION-linux-x86_64.tar.gz
    - on i386: https://julialang-s3.julialang.org/bin/linux/x86/${JULIA_RELEASE}/julia-$SNAPCRAFT_PROJECT_VERSION-linux-i686.tar.gz
    - on arm64: https://julialang-s3.julialang.org/bin/linux/aarch64/${JULIA_RELEASE}/julia-$SNAPCRAFT_PROJECT_VERSION-linux-aarch64.tar.gz
    - on armhf: https://julialang-s3.julialang.org/bin/linux/armv7l/${JULIA_RELEASE}/julia-$SNAPCRAFT_PROJECT_VERSION-linux-armv7l.tar.gz
  julia-docs:
    plugin: dump
    source: snap/local
```

and then you'd replace `${JULIA_VERSION}` and `${JULIA_RELEASE}`

**Comment by DilumAluthge** [comment]
Yeah exactly, I think just have two placeholders.

**Comment by p-zubieta** [comment]
I added a commit using the template above instead, hope you don't mind @ararslan (but feel free to dismiss it or improve it).

**Comment by ararslan** [comment]
That's perfect! I made one simplification that's possible since we're using 1.8 to run the script in CI, now I think this should be good to go. Thanks for implementing the change, this is much better than what I had initially.

**Review by p-zubieta — APPROVED** [review]

**Pull request merged**
